---
title: "Wikimedia - EDA Buscas e Sessões"
author: "Whendell Feijó Magalhães"
output:
    html_document:
        code_folding: hide
---

<style>
body{text-align: justify}
</style>


O objeto principal da análise são as buscas e a navegação depois da busca. Criamos esses dados a partir dos dados originais da wikimedia em `/data/search_data.csv`. 

Aqui, exploramos esses dados. 

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(lubridate)
library(scales)
library(broom)
library(boot)
theme_set(theme_gray())

knitr::opts_chunk$set(tidy = FALSE,
                      echo = TRUE,
                      fig.width = 8,
                      fig.height = 6,
                      fig.align = "center")

buscas = read_csv(here::here("data/search_data.csv"))

### Preprocessando os dados para criar uma nova coluna contendo unicamente o dia em que a sessão foi iniciada e removendo valores extremos que não fazem sentido com o contexto do problema (first_click > 500) 

buscas <- mutate(buscas, day = round_date(buscas$session_start_date, "day")) %>%
    group_by(session_id) %>%
    mutate(day = min(day)) %>% 
    ungroup() %>% 
    filter(is.na(first_click) | first_click <= 500)

```

###

```{r}
sessoes <- buscas %>%
    group_by(session_id, group, day) %>% 
    summarise(has_clicks = any(num_clicks > 0)) %>% 
    ungroup()

sessoes %>% 
    group_by(group) %>%
    summarise(clickthrough_rate = sum(has_clicks) / n()) -> ctr

buscas %>% 
    mutate(has_results = results > 0) %>%
    group_by(group) %>% 
    summarise(zero_results_rate = 1 - (sum(has_results) / n())) -> zrr
```

###

```{r}
theta_diferenca_clickthrough_rate = function(d, i){
    click_rate = d %>% 
        slice(i) %>% 
        group_by(group) %>%
        summarise(clickthrough_rate = sum(has_clicks) / n())
    
    group_a = click_rate %>% filter(group == "a") %>% pull(clickthrough_rate)
    group_b = click_rate %>% filter(group == "b") %>% pull(clickthrough_rate)
    
    group_a - group_b
}

theta_diferenca_zero_results_rate = function(d, i){
    zero_rate = d %>% 
        slice(i) %>% 
        mutate(has_results = results > 0) %>%
        group_by(group) %>% 
        summarise(zero_results_rate = 1 - (sum(has_results) / n()))
    
    group_a = zero_rate %>% filter(group == "a") %>% pull(zero_results_rate)
    group_b = zero_rate %>% filter(group == "b") %>% pull(zero_results_rate)
    
    group_a - group_b
}
```

### Usando IC para clickthrough_rate

```{r}
sessoes %>%
    boot(statistic = theta_diferenca_clickthrough_rate, R = 4000) %>%
    tidy(conf.level = 0.95,
         conf.int = TRUE)
```

### Usando IC para zero_results_rate

```{r}
buscas %>%
    boot(statistic = theta_diferenca_zero_results_rate, R = 4000) %>%
    tidy(conf.level = 0.95,
         conf.int = TRUE)

```

###

```{r}
theta_embaralhado_clickthrough_rate = function(d){
    click_rate = d %>% 
        mutate(group_embaralhada = sample(group, n())) %>% 
        group_by(group_embaralhada) %>%
        summarise(clickthrough_rate = sum(has_clicks) / n())
    
    group_a = click_rate %>% filter(group_embaralhada == "a") %>% pull(clickthrough_rate)
    group_b = click_rate %>% filter(group_embaralhada == "b") %>% pull(clickthrough_rate)
    
    group_a - group_b
}

theta_embaralhado_zero_results_rate = function(d){
    zero_rate = d %>% 
        mutate(group_embaralhada = sample(group, n())) %>% 
        mutate(has_results = results > 0) %>%
        group_by(group_embaralhada) %>%
        summarise(zero_results_rate = 1 - (sum(has_results) / n()))
    
    group_a = zero_rate %>% filter(group_embaralhada == "a") %>% pull(zero_results_rate)
    group_b = zero_rate %>% filter(group_embaralhada == "b") %>% pull(zero_results_rate)
    
    group_a - group_b
}

theta_embaralhado_clickthrough_rate(sessoes)

theta_embaralhado_zero_results_rate(buscas)
```
### Teste de hipótese usando permutação
